services:

  nginx:
    build: requirements/nginx/.
    ports:
      - 443:443
    container_name: nginx
    networks:
      inception:
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
    restart: always
  mariadb:
    build: ./requirements/mariadb/.
    container_name: mariadb
    env_file:
      - .env
    networks:
      inception:
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
  wordpress:
    build: ./requirements/wordpress/.
    container_name: wordpress
    env_file:
      - .env
    depends_on:
      - mariadb
    networks:
      inception:
    volumes:
      - wordpress:/var/www/wordpress
    restart: always
  ftp:
    build: ./requirements/bonus/ftp/.
    container_name: ftp
    ports:
      - 21:21
      - 20:20
      - 10000-10100:10000-10100
    env_file:
      - .env
    networks:
      inception:
    volumes:
      - wordpress:/home/ybenchel/ftp
    restart: always
  redis:
    build: ./requirements/bonus/redis/.
    container_name: redis
    networks:
      inception:
    restart: always
  adminer:
    build: ./requirements/bonus/adminer/.
    container_name: adminer
    networks:
      inception:
    ports:
      - 8080:80
    restart: always
  glances:
    build: ./requirements/bonus/glances/.
    container_name: glances
    networks:
      inception:
    expose:
      - 61208
    restart: always
  website:
    build: ./requirements/bonus/website/.
    container_name: website
    networks:
      inception:
    expose:
      - 80
    restart: always

networks:
  inception:
volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/ybenchel/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none' 
      o: 'bind'									
      device: '/home/ybenchel/data/mariadb'	